// Constants
#macro LOOK_DURATION time_to_frames(0, 2)
#macro SLIDE_DURATION 30
#macro RECOVERY_DURATION time_to_frames(0, 2)
#macro SPRING_DURATION 16
#macro TRICK_LOCK_DURATION 9

#macro INVINCIBILITY_DURATION time_to_frames(0, 20)
#macro SUPERSPEED_DURATION time_to_frames(0, 20)

// All Characters
#macro CEILING_LAND_THRESHOLD -4
#macro SLIDE_THRESHOLD 2.5
#macro ROLL_THRESHOLD 0.9921875 / 0.75
#macro UNROLL_THRESHOLD 0.5
#macro BRAKE_THRESHOLD 4
#macro AIR_THRESHOLD 4
#macro SLOPE_FRICTION 0.125
#macro ROLL_SLOPE_FRICTION_UP 0.078125
#macro ROLL_SLOPE_FRICTION_DOWN 0.3125
#macro SPIN_DASH_ATROPHY 0.96875
#macro ANIMATION_RECORD_COUNT 16
#macro AFTERIMAGE_COUNT 3
#macro SPEED_BREAK_COUNT 16

// Sonic
#macro SONIC_BOUND_FORCE 0.21875 / 0.75
#macro SONIC_BOUND_HEIGHT 6 / 0.75

// Tails
#macro TAILS_FLY_DURATION time_to_frames(0, 8)
#macro TAILS_FLY_BASE_FORCE 0.03125
#macro TAILS_FLY_ASCEND_FORCE 0.125
#macro TAILS_FLY_THRESHOLD -1

// Knuckles
#macro KNUCKLES_GLIDE_ACCELERATION 0.015625
#macro KNUCKLES_GLIDE_SLIDE_FRICTION 0.125
#macro KNUCKLES_CLIMB_SPEED 1

enum AERIAL_FLAG
{
	NONE = (1 << 0),
	PLATFORM = (1 << 1),
	SHIELD_ACTION = (1 << 2),
	BOUND = (1 << 3),
	FORWARD_THRUST = (1 << 4),
}

enum CHARACTER
{
	NONE = -1, SONIC, CREAM, TAILS, KNUCKLES, AMY, MAX
}

enum PHASE
{
	ENTER, STEP, EXIT
}

enum TRICK_TYPE
{
	UP, DOWN, FRONT, BACK
}

enum SHIELD_TYPE
{
	NONE, BASIC, MAGNETIC
}

enum PLAYER_ANIMATION
{
	IDLE, TURN, RUN, BRAKE, APPEAL, CROUCH,
	ROLL, SPIN_DASH, FALL, JUMP,
	HURT, DEAD, BEFORE_COUNTDOWN,
	TRICK_UP, TRICK_DOWN, TRICK_FRONT, TRICK_BACK, 
	SPRING, SPRING_TWIRL, DASH,
	MAX
}

enum SONIC_ANIMATION
{
	INSTA_SHIELD = PLAYER_ANIMATION.MAX,
	FORWARD_THRUST, SKIDDING,
}

enum TAILS_ANIMATION
{
	FLYING = PLAYER_ANIMATION.MAX,
	FLYING_TURN, FLYING_TIRED,
	SWIPE, SUPER_SWIPE,
}

enum KNUCKLES_ANIMATION
{
	GLIDE = PLAYER_ANIMATION.MAX,
	GLIDE_TURN, GLIDE_SLIDING, GLIDE_FALL,
	CLIMB_ATTACH, CLIMB, // <-- This includes the idle, movement, lifting upwards and landing animations
	PUNCH, SPIRAL_ATTACK,
}