// Constants
#macro LOOK_DURATION time_to_frames(0, 2)
#macro SLIDE_DURATION 30
#macro RECOVERY_DURATION time_to_frames(0, 2)
#macro SPRING_DURATION 16
#macro TRICK_LOCK_DURATION 9

#macro INVINCIBILITY_DURATION time_to_frames(0, 20)
#macro SUPERSPEED_DURATION time_to_frames(0, 20)

// All Characters
#macro CEILING_LAND_THRESHOLD -4
#macro SLIDE_THRESHOLD 2.5
#macro ROLL_THRESHOLD (1 - (2 / 256))
#macro UNROLL_THRESHOLD 0.5
#macro BRAKE_THRESHOLD 4
#macro LOW_AIR_THRESHOLD -3
#macro HIGH_AIR_THRESHOLD 0
#macro SLOPE_FRICTION 0.125
#macro SPIN_DASH_ATROPHY 0.96875
#macro ANIMATION_RECORD_COUNT 16
#macro AFTERIMAGE_COUNT 3
#macro SPEED_BREAK_COUNT 16

// Sonic
#macro SONIC_BOUND_FORCE (56 / 256)
#macro SONIC_BOUND_HEIGHT 6
#macro SONIC_BOUND_FRAME_COUNT 5

// Tails
#macro TAILS_FLY_DURATION time_to_frames(0, 8)
#macro TAILS_FLY_BASE_FORCE (8 / 256)
#macro TAILS_FLY_ASCEND_FORCE (24 / 256)
#macro TAILS_FLY_THRESHOLD -0.75

// Knuckles
#macro KNUCKLES_GLIDE_FAST_ACCELERATION (6 / 256)
#macro KNUCKLES_GLIDE_SLOW_ACCELERATION (3 / 256)
#macro KNUCKLES_GLIDE_SLIDE_FRICTION (24 / 256)
#macro KNUCKLES_CLIMB_SPEED 0.75

// Amy
#macro AMY_HEART_COUNT 4

enum AERIAL_FLAG
{
	NONE = (1 << 0),
	PLATFORM = (1 << 1),
	SHIELD_ACTION = (1 << 2),
	BOUND = (1 << 3),
	FORWARD_THRUST = (1 << 4),
}

enum CHARACTER
{
	NONE = -1, SONIC, CREAM, TAILS, KNUCKLES, AMY, MAX
}

enum PHASE
{
	ENTER, STEP, EXIT
}

enum TRICK_TYPE
{
	UP, DOWN, FRONT, BACK
}

enum SHIELD_TYPE
{
	NONE, BASIC, MAGNETIC
}

enum PLAYER_ANIMATION
{
	IDLE, TURN, RUN, BRAKE, APPEAL, CROUCH,
	ROLL, SPIN_DASH, FALL, JUMP,
	HURT, DEAD, BEFORE_COUNTDOWN,
	TRICK_UP, TRICK_DOWN, TRICK_FRONT, TRICK_BACK, 
	SPRING, SPRING_TWIRL, DASH,
	MAX
}

enum SONIC_ANIMATION
{
	INSTA_SHIELD = PLAYER_ANIMATION.MAX,
	FORWARD_THRUST, SKIDDING,
}

enum TAILS_ANIMATION
{
	FLYING = PLAYER_ANIMATION.MAX,
	FLYING_TURN, FLYING_TIRED,
	SWIPE, SUPER_SWIPE,
}

enum KNUCKLES_ANIMATION
{
	GLIDE = PLAYER_ANIMATION.MAX,
	GLIDE_TURN, GLIDE_SLIDING, GLIDE_FALL,
	CLIMB_ATTACH, CLIMB, // <-- This includes the idle, movement, lifting upwards and landing animations
	PUNCH, SPIRAL_ATTACK,
}

enum SONIC_EFFECT_TYPE
{
	SLIDE_ATTACK, INSTA_SHIELD, BOUND
}

enum KNUCKLES_FLAME_TYPE
{
	SPIRAL_ATTACK, DRILL_CLAW
}

enum AMY_HEART_TYPE
{
	HAMMER_ATTACK, W_HAMMER_ATTACK, AERIAL_HAMMER_ATTACK, HAMMER_WHIRL
}